server:
  port: 4000

spring:
  application:
    name: OrderApp
  datasource:
    url: jdbc:postgresql://${HOST_WILL BE WRITTEN:localhost}:${PORT_WILL BE WRITTEN:5432}/${DB_NAME_WILL BE WRITTEN:OrderApp}
    username: postgres
    password: password1
    hikari:
      connection-timeout: 3600000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
